aloneguid/parquet-dotnet

src/Parquet.Test/EndToEndTypeTest.cs
src/Parquet.Test/StatisticsTest.cs
src/Parquet/File/Values/Primitives/NanoTime.cs

For the writing part this would be a breaking change.
This PR converts the `DateTimeOffset` to universal time before converting it the INT96.
Currently parquet-dotnet appears to write everything as is, so any local offset would be lost when writing.  When reading it back in it would be read as if it was a UTC `DateTimeOffset` (which then of course gives a different time instant than what the user attempted to write).

Local time offset was lost when writing DateTimeOffset in non UTC format

---

src/Parquet.CLI/Help.Designer.cs
src/Parquet.CLI/Help.resx
src/Parquet.Test/Parquet.Test.csproj
src/Parquet.Test/Serialisation/ParquetConvertTest.cs
src/Parquet/Data/Schema/Schema.cs
src/Parquet/Parquet.csproj
src/Parquet/Serialization/SchemaReflector.cs
src/Parquet/Serialization/Values/MSILGenerator.cs

Issue #29 
`[ParquetColumn]` was totally ignored on deserialisation, so it fails with renamed column

[ParquetColumn] was totally ignored on deserialization

---

doc/serialisation.md
src/Parquet.Test/Serialisation/ParquetConvertTest.cs
src/Parquet/Attributes/ParquetIgnoreAttribute.cs
src/Parquet/Serialization/SchemaReflector.cs

- ParequetConvert serialize API should ignore properties marked with
ignore attribute during serailization process to parquet file.
Issue #28 
desctiption goes here
[YES] I have included unit tests validating this fix.
[YES] I have updated markdown documentation where required.
[ YES] I understand that successful approval of my pull request requires reproducible tests as per  [Contribution Guideline](https://github.com/aloneguid/parquet-dotnet/blob/master/.github/CONTRIBUTING.md).

Enhancement #28: Add ability to ignore properties

---

src/Parquet.Test/Rows/RowsModelTest.cs
src/Parquet/Data/Rows/DataColumnAppender.cs
src/Parquet/Data/Rows/LevelIndex.cs
src/Parquet/Data/Rows/RowsToDataColumnsConverter.cs
src/Parquet/Extensions/CollectionExtensions.cs

Issue #42 
This PR fixes an issue with incorrect repetition levels when writing a table that has nested list fields. 
The suggested implementation uses an array of [LocationIndex](https://github.com/rickykaare/parquet-dotnet/blob/458-nested-listfields/src/Parquet/Data/Rows/LevelIndex.cs)s to keep track of the indexes of the lists at all preceding levels, and uses this information to identify which level is changing its index (repetition level).
Changes include:
* [`881064f`](https://github.com/aloneguid/parquet-dotnet/commit/881064fb9223dfde7df595966804bbd340b1d799) Introduce LevelIndex to hold index information for each list in the path
* [`8a53ca6`](https://github.com/aloneguid/parquet-dotnet/commit/8a53ca637c093d811101c9e2a2a23a9f38e8cf4a) Introduce extension method for appending …

Fix issue with repetition levels when having nested lists in a table

---

src/Parquet.Test/Integration/ParquetMrIntegrationTest.cs
src/Parquet/Data/Concrete/ByteDataTypeHandler.cs
src/Parquet/Data/Concrete/Int16DataTypeHandler.cs
src/Parquet/Data/Concrete/SignedByteDataTypeHandler.cs
src/Parquet/Data/Concrete/UnsignedInt16DataTypeHandler.cs

Issue #16 
Previously `(s)byte` and `(u)short` were serialized incorrectly. The Apache Parquet format requires them to be written as 32 bit integers. I've create a test using the **parquet-tools.jar** which failed previous to my fix and now succeeds.

16 integer serialization

---

src/Parquet.Test/Reader/TestDataTest.cs
src/Parquet.Test/Rows/RowsModelTest.cs
src/Parquet/Data/Rows/DataColumnsToRowsConverter.cs
src/Parquet/Data/Rows/RowsToDataColumnsConverter.cs
src/Parquet/ParquetRowGroupWriter.cs

Issue #49 
This PR fixes an issue with reading and writing a table with empty values for a list field of structures.
The suggested implementation extracts the logic of initializing the `DataColumnAppender`s to a method used to access the `_pathToDataColumn` dictionary. This way even the columns without data will be able to resolve an appender and produce a `DataColumn`.
Two other issues was found and fixed during testing:
* issue with reading Tables with an empty list field of structs
* issue with writing wrong RowCount when first field is empty ListField
Changes include:
* [`3bf79bc`](https://github.com/aloneguid/parquet-dotnet/commit/3bf79bcf58dcd80aa8bce9a7de055aa7bf51f1cc) Fix KeyNotFoundException: Use accessor method for dictionary
* …

Fix issue with reading and writing table with empty list field of structs

---

src/Parquet/Parquet.csproj

update nuget package, fix IronSnappy encode break issue
update nuget package, fix IronSnappy encode break issue

update nuget package, fix IronSnappy encode break issue

---

doc/serialisation.md
src/Parquet.Test/Serialisation/ParquetConvertTest.cs
src/Parquet/ParquetConvert.cs

- Serialize all properties and deserialize only few properties
Issue #
Current de-serialization doesn't support retrieving few properties.
- [Yes ] I have included unit tests validating this fix.
- [ Yes] I have updated markdown documentation where required.
- [Yes ] I understand that successful approval of my pull request requires reproducible tests as per [Contribution Guideline](https://github.com/aloneguid/parquet-dotnet/blob/master/.github/CONTRIBUTING.md).

Deserialize only few properties 

---

README.md
src/Parquet.Test/EndToEndTypeTest.cs
src/Parquet/Attributes/ParquetColumnAttribute.cs
src/Parquet/Data/Concrete/TimeSpanDataTypeHandler.cs
src/Parquet/Data/DataType.cs
src/Parquet/Data/DataTypeFactory.cs
src/Parquet/Data/Schema/TimeSpanDataField.cs
src/Parquet/Data/TimeSpanFormat.cs
src/Parquet/Parquet.csproj
src/Parquet/Serialization/SchemaReflector.cs

Issue #
add TimeSpan DataField support, MilliSeconds(INT32), MicroSeconds(INT64). ParquetColumnAttribute add TimeSpanFormat and DateTimeFormat, support custom SchemaReflector define.

add TimeSpan DataField support

---

src/Parquet/Data/ArrayView.cs
src/Parquet/Data/BasicDataTypeHandler.cs
src/Parquet/Data/BasicPrimitiveDataTypeHandler.cs
src/Parquet/Data/Concrete/BooleanDataTypeHandler.cs
src/Parquet/Data/Concrete/ByteArrayDataTypeHandler.cs
src/Parquet/Data/Concrete/DateTimeOffsetDataTypeHandler.cs
src/Parquet/Data/Concrete/DecimalDataTypeHandler.cs
src/Parquet/Data/Concrete/IntervalDataTypeHandler.cs
src/Parquet/Data/Concrete/StringDataTypeHandler.cs
src/Parquet/Data/Concrete/TimeSpanDataTypeHandler.cs
src/Parquet/Data/DataColumn.cs
src/Parquet/Data/IDataTypeHandler.cs
src/Parquet/Data/NonDataDataTypeHandler.cs
src/Parquet/Data/WritableArrayView.cs
src/Parquet/File/DataColumnWriter.cs
src/Parquet/File/StringListComparer.cs
src/Parquet/File/ThriftFooter.cs

Issue #84 
Before these changes the use case took 107,716ms to complete.  After each of these changes the time is 10,232ms.
**Note** The total time is the end-to-end test, now Parquet.net is a small part of the overhead of the conversion algorithm, where before it was the majority of the time. 
This screen shot shows the performance after all the refactoring.
**Reuse `ThriftSchemaTree` to reduce GC overhead.**
To resolve this I construct the `ThriftSchemaTree` in the `ThriftFooter` so it doesn't need to be created for each call to `GetPath`.  The impact of this change is shown here:
**Introduce ArrayView**
1. Remove the LINQ multiple enumerations of the data and overhead associated with allocations of LINQ Count used to allocate the new array allocated in PackDefinitions.
1. Reduce GC …

Write performance improvements

---

src/Parquet/Data/Schema/DataField.cs

Issue #74 
Make `ClrType` and `ClrNullableIfHasNullsType` public from internal. 
As this is a trivial change, I added no test. I do not see any MD to update for this change.

Make ClrType public from internal and update comment.

---

src/Parquet/File/DataColumnReader.cs

Sometimes parquet files generated by spark contain a page full of nulls. These pages have zero size and parquet.net fails with System.IO.EndOfStreamException.
The ReadRleBitpackedHybrid function interprets zero length as an instruction to read the actual length from the stream. ReadLevels relies on this behavior, however, zero can be a valid length when reading a plain dictionary page.
I decided not to mess with ReadRleBitpackedHybrid implementation and instead check that length is zero and skip the remaining items

Fix reading of plain dictionary with zero length

---

src/Parquet/File/Values/RunLengthBitPackingHybridValuesReader.cs

Fix #81
The method that reads from bit packed data, RunLengthBitPackingHybridValuesReader.ReadBitpacked, was incorrectly using arithmetic shift instead of logical shift. Causing data corruption when the accumulator variable is greater than int.MaxValue.
This change is critical, please double check my changes

Fix RunLengthBitPackingHybridValuesReader.ReadBitpacked. Fix #81

---

src/Parquet/File/DataColumnReader.cs

Fixes #88 
**Allows for there to be no RLE or Bitpacked values on a data page.** On occasion I find Spark creates these 'empty' pages. They have a valid header, and accurate byte counts, but no values.
I'm not clear whether these are allowed by the spec... but they are 'de facto' correct: Spark writes them; Python/pandas can read them ok.
There is no test in this PR. [This Gist contains the test I use locally, unfortunately I cannot share the file that goes with it.](https://gist.github.com/ishepherd/f06deae5c06ecc040de0662a865de5a7)
⚠️ Help needed. @peteriehl can you help to provide a repro file?

Avoid EndOfStreamException with empty pages

---

src/Parquet.Test/DataFieldTypeCoverageTests.cs
src/Parquet/Data/Concrete/Int16DataTypeHandler.cs
src/Parquet/Data/Concrete/ShortDataTypeHandler.cs
src/Parquet/Data/Concrete/UnsignedByteDataTypeHandler.cs
src/Parquet/Data/Concrete/UnsignedInt16DataTypeHandler.cs
src/Parquet/Data/Concrete/UnsignedShortDataTypeHandler.cs
src/Parquet/Data/DataTypeFactory.cs

Copy of https://github.com/elastacloud/parquet-dotnet/pull/488
Adds/corrects the `DataType` to `BasicPrimitiveDataTypeHandler` mapping, solving the NullReference-Exception bug.
Issue #114
Not all values of the `DataType` enum had mappings to appropriate instances of `BasicPrimitiveDataTypeHandler` in `DataTypeFactory`, which I believe caused the unmatched types to be resolved to default objects in `_allDataTypes.FirstOrDefault(dt => dt.DataType == dataType)`, and that caused some of the fields of the `DataType` object to be null.
This PR adds and corrects `BasicPrimitiveDataTypeHandler`s so that every value of the `DataType` enum is mapped to an appropriate handler, solving the NullReference-Exception bug.
Fix is accompanied with a unit test which shows that objects created from all …

 Fix for NullReference-Exception in case of Int16, UnsignedShort and UnsignedByte

---

src/Parquet/Attributes/ParquetColumnAttribute.cs
src/Parquet/Serialization/SchemaReflector.cs

default scale and precision is used for decimals
Issue #
I followed the same methodology used for DateTime

Add support for decimal scale and precision

---

src/Parquet.Test/File/Values/Primitives/NanoTimeTest.cs
src/Parquet/File/Values/Primitives/NanoTime.cs

Issue #111 
Replace AddMilliseconds by AddTicks method to preserve ticks during the conversion from NanoTime to DateTimeOffset.

Preserve ticks during the conversion from NanoTime to DateTimeOffset

---

src/Parquet.Test/Serialisation/ParquetConvertTest.cs
src/Parquet/Attributes/ParquetColumnAttribute.cs
src/Parquet/Data/Concrete/DecimalDataTypeHandler.cs
src/Parquet/Data/DecimalFormatDefaults.cs

Issue #131 
Fix breaking changes from v3.9 whereby new support for explicitly controlling Decimal precision and scale did not include support for previously existing default values. The changes introduced no longer allowed existing code to use defaults that were originally supported prior to v3.9.  
This is easily resolved by ensuring that the new properties available on `ParquetColumnAttribute` to provide clear default values when not explicitly defined by consumers.
The use case here is when we merely want to rename a `decimal` column like any other column; therefore this is now covered by the unit test `Serialise_deserialise_renamed_column` test.  The `Serialise_deserialise_renamed_column` test now passes successfully; but was failing during serialization & de-serialization when test …

Fix breaking change in v3.9 due to missing default fallback for Decimal Precision/Scale

---

src/Parquet.Test/ParquetWriterTest.cs
src/Parquet.Test/SchemaTest.cs
src/Parquet/Data/Schema/Schema.cs

[Issue #134](https://github.com/aloneguid/parquet-dotnet/issues/134)
`System.Object.Equals()` equality should not be relied upon for two custom complex objects in C#.
This was further exacerbated because of type, nullable, and boxing.

Fix Field equality in SchemaValidation inside ParquetWriter.

---

src/Parquet/Data/Concrete/StringDataTypeHandler.cs

Issue #161 
Use buffer from **ArrayPool\<byte\>** for string encoding to reduce RAM allocation

161 Reuse buffer for string encoding from ArrayPool<byte>

---

src/Parquet.Test/DecimalTypeTest.cs
src/Parquet/Data/Schema/DecimalDataField.cs

We noticed that the decimal field scale field is not according to spec, please let me know what you think of the solution.
Issue #
decimal field not following spec
https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#decimal for more details.
- [ x] I have included unit tests validating this fix.
- [ docs pointing to class with updates] I have updated markdown documentation where required.
- [x ] I understand that successful approval of my pull request requires reproducible tests as per [Contribution Guideline](https://github.com/aloneguid/parquet-dotnet/blob/master/.github/CONTRIBUTING.md).

Implement decimal validation according to spec

---

src/Parquet/Data/DataColumn.cs
src/Parquet/Data/Schema/DataField.cs
src/Parquet/File/DataColumnReader.cs
src/Parquet/Serialization/Values/ClrBridge.cs
src/Parquet/Serialization/Values/MSILGenerator.cs

Issue when Deserializing a file that has been saved with Python or C# including a nullable Boolean.
Before, it was mapped to wrong output (False -> True, True -> False) when Deserializing (in the generic IL code).
I am certain that the fix is not ready to be merged in current state, but wanted to raise PR to get awareness on issue,
and work with you to make the perfect fix.
The code in the current state maps correctly for both nullable and not nullable booleans:
Nullable Null -> False
Nullable True -> True
Nullable False -> False
False -> False
True -> True
* Inclusion of a NullableBooleanToBoolean converter.
* When detecting that data is in fact Nullable Boolean, change the CLR type on DataField (required making setter public)
* When invokink GenerateAssigner, use DataField definition …

Enable support for nullable Boolean

---

src/Parquet.Test/ParquetWriterTest.cs
src/Parquet/Data/ArrayView.cs
src/Parquet/Data/BasicDataTypeHandler.cs
src/Parquet/Data/BasicPrimitiveDataTypeHandler.cs
src/Parquet/Data/Concrete/ByteArrayDataTypeHandler.cs
src/Parquet/Data/Concrete/StringDataTypeHandler.cs
src/Parquet/Data/DataColumn.cs
src/Parquet/Data/IDataTypeHandler.cs
src/Parquet/Data/NonDataDataTypeHandler.cs
src/Parquet/Data/WritableArrayView.cs
src/Parquet/File/DataColumnWriter.cs
src/Parquet/ParquetRowGroupWriter.cs

The `WriteColumn` method on `ParquetRowGroupWriter` now accepts offset and count.
Issue #108
When writing large columns it was somewhat inefficient to have to allocate exactly correctly sized arrays. This new overload allows one to use shared arrays, for instance those from `ArrayPool<T>`, which may be larger than the length requested and thus require reading only a subset of the array.
I've made the changes and verified no breakages, and I've added two new (simple) tests for the new cases. But there may be subtleties that I'm not aware of and thus haven't covered by tests.

Accept offset and count on array parameters

---

src/Parquet/File/Values/Primitives/NanoTime.cs

NanoTime 1721424 equals to 0000-12-30 (YYYY-MM-DD) but DateTimeOffset.MinValue is 0001-01-01 => change Year to 1 (any better solution ?)

FIX: Check if Year is 0, set it to 1 then

---

src/Parquet.Test/File/Values/Primitives/NanoTimeTest.cs
src/Parquet/File/Values/Primitives/NanoTime.cs

Issue #111 
Fix precision issue with conversion double -> long

Preserve ticks precision

---

src/Parquet/ParquetExtensions.cs

Avoid an error when using `foreach (Row row in parquetReader.ReadAsTable())`for example

ReadAsTableAsync: Return an empty table if there is no row

---

src/Parquet.Test/DumbStreamTest.cs
src/Parquet/File/DataColumnReader.cs

Issue #188
- Fixed bug in ReadPageData where it did not read all the page bytes from the stream

Fixed #188 - Reading full page from stream

---

src/Parquet.Test/Parquet.Test.csproj
src/Parquet.Test/ParquetWriterTest.cs
src/Parquet/3rdparty/MeteredWriteStream.cs
src/Parquet/ParquetRowGroupWriter.cs
src/Parquet/ParquetWriter.cs

Issue #192
Fixes a regression from 3.x where write-only streams throw an exception.

Make ParquetWriter work with write-only streams

---

src/Parquet/File/DataColumnReader.cs

Issue #232 
* Use DataBuffer for ensuring array returned to ArrayPool.Shared
* Use 'using' when creating MemoryStream

232 fix ReadDataPageV2Async memory handling

---

src/Parquet.Test/Integration/ParquetMrIntegrationTest.cs
src/Parquet.Test/StatisticsTest.cs

I'm not sure if stats DateTime behaviour is what you want (for non-GMT TZs).
The other change allows for spaces in path names.

Changes to test code to run on my machine

---

src/Parquet/ParquetConvert.cs

This `new()` constraint is not necessary for `Serialize` methods. With the constraint, one cannot serialize types that have the new `required` keyword added for properties in C# 11 ([refer to documentation](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/required)).

Remove `new()` constraint for Serialize methods

---

.github/workflows/full.yml
docs/serialisation.md
src/Parquet.PerfRunner/Program.cs
src/Parquet.Test/File/Values/Primitives/BigDecimalTest.cs
src/Parquet.Test/Schema/SchemaTest.cs
src/Parquet.Test/Serialisation/SchemaReflectorTest.cs
src/Parquet.Test/TestBase.cs
src/Parquet.Test/Types/EndToEndTypeTest.cs
src/Parquet/Data/DecimalFormatDefaults.cs
src/Parquet/Encodings/ParquetPlainEncoder.cs
src/Parquet/Encodings/SchemaEncoder.cs
src/Parquet/Extensions/OtherExtensions.cs
src/Parquet/Extensions/SpanExtensions.cs
src/Parquet/File/ThriftFooter.cs
src/Parquet/Parquet.csproj
src/Parquet/ParquetOptions.cs
src/Parquet/Schema/TimeSpanDataField.cs
src/Parquet/Serialization/Attributes/ParquetDecimalAttribute.cs
src/Parquet/Serialization/Attributes/ParquetMicroSecondsTimeAttribute.cs
src/Parquet/Serialization/Attributes/ParquetTimestampAttribute.cs
src/Parquet/Serialization/ParquetSerializer.cs
src/Parquet/Serialization/ParquetSerializerOptions.cs
src/Parquet/Serialization/TypeExtensions.cs

- low-level: full logical types support in Parquet Thrift schema
- class serializer supports custom attributes to customize serialisation of dates, times, and decimals.
- added support for .NET 6 `DateOnly` type.

Library-Wide Schema improvements

---

src/Parquet.Test/ParquetEncoderTest.cs
src/Parquet.Test/Serialisation/SchemaReflectorTest.cs
src/Parquet.Test/Types/EndToEndTypeTest.cs
src/Parquet/Encodings/ParquetPlainEncoder.cs
src/Parquet/Encodings/SchemaEncoder.cs
src/Parquet/Extensions/SpanExtensions.cs
src/Parquet/Extensions/UntypedArrayExtensions.cs
src/Parquet/Extensions/UntypedArrayExtensions.tt
src/Parquet/ParquetOptions.cs
src/Parquet/Schema/TimeOnlyDataField.cs
src/Parquet/Serialization/TypeExtensions.cs

This pull request adds support to TimeOnly while trying to be as similar as possible to TimeSpan.
TimeOnly is more expressive when serializing data meant to be a time of the day rather than an interval of time. Too new fields are added to ParquetOptions to select TimeOnly instead of TimeSpan for deserializing: UseTimeOnlyTypeForTimeMillis (for time fields with millisecond precision) and UseTimeOnlyTypeForTimeMicros for selecting TimeOnly when one finds a time field with microsecond precision. This is similar to the filed UseDateOnlyTypeForDates for choosing DateOnly.
Best regards.

Add support to .NET 6 TimeOnly type

---

src/Parquet.Test/Extensions/OtherExtensionsTest.cs
src/Parquet/Extensions/OtherExtensions.cs

Fixes #312 by switching to [DateTimeOffset.ToUnixTimeMilliseconds](https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset.tounixtimemilliseconds) instead of a custom implementation to keep things simple.
The first and third test cases fail without this change and all three pass with this change. I didn't know if there were any tests that actually write a parquet file and read it back that I should update. This PR just tests the method being modified.

Fix precision issues writing DateTime as milliseconds

---

src/Parquet/File/DataColumnWriter.cs

In DataColumnWriter, RecycableMemoryStream wasn't used in a particular case, and instead MemoryStream was initialized directly.

Use RecycableMemoryStream in DataColumnWriter

---

src/Parquet.Test/Encodings/DeltaBinaryPackedEncodingTest.cs
src/Parquet/Encodings/DeltaBinaryPackedEncoder.Variations.cs
src/Parquet/Encodings/DeltaBinaryPackedEncoder.Variations.tt
src/Parquet/Encodings/DeltaBinaryPackedEncoder.cs
src/Parquet/Extensions/EncodingExtensions.cs

- Ensuring delta encoding footer blocks are complete
- backward compatible for polars, data bricks warehouse etc.
- Handle Overflow: Using MSB position to calculate bit width 
-  Issue: https://github.com/aloneguid/parquet-dotnet/issues/389
-  ref : parquet-mr : https://github.com/apache/parquet-mr/blob/master/parquet-column/src/main/java/org/apache/parquet/column/values/delta/DeltaBinaryPackingValuesWriterForInteger.java#L152

Ensuring delta encoding footer blocks are complete And Handle Overflow

---

src/Parquet/Data/DataColumn.cs
src/Parquet/File/DataColumnWriter.cs

Part of #375. If a column only contains null values, the array passed to `DeltaBinaryPackedEncoder` will be empty and cause the encoder to return without writing a header. This breaks compatibility with some readers such as Apache parquet-mr that try to read the header.
I verified writing a parquet file containing such a column can be read by parquet-mr with this change but failed before.

Use PLAIN encoding for columns without defined data

---

src/Parquet/Serialization/ParquetSerializer.cs

Add a new public method that matches the existing deserialization functionality but operates on open `RowGroupReaders` rather than opening and closing a `ParquetReader` for every row group.
Closes #422

Allow deserialization from open RowGroupReaders.

---

src/Parquet/Serialization/ParquetSerializer.cs

The size of every row group is known from the metadata as soon as the reader is initialized. This can be used when creating the buffer list to prevent the need to optimize the list capacity (which involves creating and copying new array, and making sure the array is no larger than will be required.)
(You can't actually [currently] create a list with a capacity greater than `int.MaxValue`, but I wanted to delegate that exception to runtime as if this optimization was never made instead of throwing pre-emptively.)

Preallocate result list capacity when serializing

---

src/Parquet.Test/DecimalTypeTest.cs
src/Parquet/Schema/DecimalDataField.cs

fix: decimal scale condition

---

.github/workflows/build.yml
src/Parquet.Test/ParquetReaderTest.cs
src/Parquet/ParquetReader.cs
src/Parquet/ParquetRowGroupReader.cs

Row group readers are created up-front and held in a list, so the `OpenRowGroupReader` method is just a wrapper around `list[n]`.
There is a note in the reader's `Dispose` method that says that although dispose is not required, it may be in the future so clients so clients have to take on extra ceremony. But the current design is super fast and efficient even with very large numbers of row groups, so it shouldn't be necessary.
By clarifying that `Dispose` isn't required, this enables a simple `ParquetReader.RowGroups` property that exposes a read-only list of row group readers. This then enables Linq chained expressions to operate on row groups, use `Reverse` to read from the end, `Where` to filter on column stats, and `ToAsyncEnumerable().SelectManyAwait` to deserialise into a stream of …

ParquetReader.RowGroups property

---

src/Parquet.Test/Schema/SchemaTest.cs
src/Parquet.Test/Serialisation/SchemaReflectorTest.cs
src/Parquet.Test/Types/EndToEndTypeTest.cs
src/Parquet/Encodings/ParquetPlainEncoder.cs
src/Parquet/Encodings/SchemaEncoder.cs
src/Parquet/Extensions/OtherExtensions.cs
src/Parquet/Schema/DateTimeDataField.cs
src/Parquet/Schema/DateTimeFormat.cs
src/Parquet/Schema/DateTimeTimeUnit.cs
src/Parquet/Serialization/Attributes/ParquetTimestampAttribute.cs
src/Parquet/Serialization/TypeExtensions.cs

Resolves #492
https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#timestamp

feat: Logical Timestamp

---

src/Parquet.Test/DataAnalysis/DataFrameReaderTest.cs
src/Parquet.Test/DictionaryEncodingTest.cs
src/Parquet.Test/Rows/RowsModelTest.cs
src/Parquet.Test/Serialisation/SchemaReflectorTest.cs
src/Parquet/Encodings/ParquetPlainEncoder.cs
src/Parquet/Extensions/TypeExtensions.cs
src/Parquet/Parquet.csproj
src/Parquet/ParquetExtensions.cs
src/Parquet/Schema/DataField.cs
src/Parquet/Serialization/TypeExtensions.cs
src/Parquet/Utils/NullableChecker.cs

This is a fix for bug #535. The current parquet.net doesn't leverage compiler nullable when checking if members are nullable. This affects all classes - so any `string` property was marked as nullable in the schema. This PR adds checks for [Roslyn's annotations](https://github.com/dotnet/roslyn/blob/main/docs/features/nullable-metadata.md) to ensure that a field is nullable.
- Added checks for roslin compiler attributes to properly identify nullable and not nullable classes
- Added supporting unit tests

Support for Roslyn nullable annotations

---

src/Parquet/Encodings/ParquetPlainEncoder.cs

Solves #542 
Caused by `Decode` was returning the length of the source divided by the sizeof(T) instead of the length of the actually decoded data.

Fix return of Decode methods to returning the actual destination length.

---

src/Parquet.Test/Serialisation/ParquetSerializerTest.cs
src/Parquet.Test/Serialisation/SchemaReflectorTest.cs
src/Parquet/Serialization/TypeExtensions.cs

Nullable Enums are not correctly unwrapped to the primitive type

fix: Handle nullable enums

---

src/Parquet/Serialization/TypeExtensions.cs

Attributes decorating a list-type class member are not accessible to ConstructDataField when creating the element data field.  This commit passes the ClassMember object representing the list down to ConstructListField so that it can pass it to MakeField for the list element.  This allows decorating a list of strings with, for example, ParquetRequired, so that the list elements are not nullable.  Or a list of DateTimes as ParquetTimestamp, to control how the DateTime elements are serialized.

Pass property attributes down to list data field

---

src/Parquet.Test/Serialisation/SchemaReflectorTest.cs
src/Parquet/Serialization/Attributes/ParquetTimestampAttribute.cs

Missed `IsAdjustedToUTC` in `ParquetTimestampAttribute`.
Default it to true because a local timestamp should be the exception.
Haven't thought through exactly how this would behave backwards compat. Will try to find time to setup a test where we convert from a non logical timestamp to a logical one to check the behaviour

fix: Make isAdjustedToUTC defualt to true and allow it to be set

---

src/Parquet.Test/Serialisation/AdditionalDremelStriperTests.cs
src/Parquet/Serialization/Dremel/FieldStriperCompiler.cs

Fixes #630 .
Note, I think this case also doesn't work properly for deserialization, but I didn't look into that much (not needed for my use case).

Fix #630 Calculate empty and null DL for nullable items

---

docs/README.md

Thanks to Parquet-dotnet FastBCP is ultra fast to generate parquet files from databases with parallelism and potentially partitionning

Update README.md - add FastBCP in the "Used By" section
