aloneguid/parquet-dotnet

azure-pipelines.yml, src/Parquet.CLI/Program.cs, src/Parquet/Data/Concrete/StringDataTypeHandler.cs
=> var len strings

doc/reading.md, doc/writing.md, src/Parquet.Test/ParquetWriterTest.cs, src/Parquet/File/ThriftFooter.cs, src/Parquet/ParquetReader.cs, src/Parquet/ParquetWriter.cs
Issue #17
desctiption goes here
=> add support for reading and writing custom metadata (#17)

doc/serialisation.md, src/Parquet.Test/Serialisation/ParquetConvertTest.cs, src/Parquet/ParquetConvert.cs
- Add ability to read and deserialize records by row group index
Issue #27 
desctiption goes here
- [YES ] I have included unit tests validating this fix.
- [ YES] I have updated markdown documentation where required.
- [ YES] I understand that successful approval of my pull request requires reproducible tests as per [Contribution Guideline](https://github.com/aloneguid/parquet-dotnet/blob/master/.github/CONTRIBUTING.md).
=> Enhancement#27: Read and de-serialize records by rowgroup index

src/Parquet.Test/SchemaTest.cs, src/Parquet/Data/Schema/Field.cs
Issue #
https://github.com/aloneguid/parquet-dotnet/issues/82
desctiption goes here
=> Allows Dots in field name. Fix #82

src/Parquet/Parquet.csproj
Fix a minor typo in the package description.
=> fix typo in package description.

src/Parquet/ParquetActor.cs
Just correcting the text in an error message.
=> Corrected error message

docs/README.md
=> Is this code correct/

src/Parquet.Test/SchemaTest.cs, src/Parquet/Extensions/ThriftExtensions.cs, src/Parquet/File/ThriftFooter.cs, src/Parquet/File/Values/Primitives/BigDecimal.cs, src/Parquet/ParquetRowGroupReader.cs, src/Parquet/Schema/FieldPath.cs
Issue #143 
More reliable path search. Allows to have columns with duplicate names if they are on different nesting levels too.
=> "root" column

src/Parquet/Schema/DataType.cs
This is for #244. Just fixing a tiny typo.
=> Fix signedbyte typo

src/Parquet.Test/Rows/RowsModelTest.cs, src/Parquet/Globals.cs, src/Parquet/Rows/DataColumnAppender.cs, src/Parquet/Rows/RowValidator.cs, src/Parquet/Rows/RowsToDataColumnsConverter.cs
=> support null entries in structures

.github/workflows/full.yml, src/NetBox.cs, src/Parquet.PerfRunner/Parquet.PerfRunner.csproj, src/Parquet.PerfRunner/Program.cs, src/Parquet/3rdparty/Thrift/Transport/Client/TMemoryBufferTransport.cs, src/Parquet/Extensions/StreamExtensions.cs, src/Parquet/File/DataColumnReader.cs, src/Parquet/File/DataColumnWriter.cs, src/Parquet/File/ThriftFooter.cs, src/Parquet/File/ThriftStream.cs, src/Parquet/ParquetActor.cs, src/Parquet/ParquetReader.cs, src/Parquet/ParquetRowGroupReader.cs, src/Parquet/ParquetRowGroupWriter.cs, src/Parquet/ParquetWriter.cs
=> minimize number of streaming calls when reading and writing thrift metadata

docs/serialisation.md, src/Parquet.Test/Serialisation/ParquetSerializerTest.cs, src/Parquet/Serialization/ParquetSerializer.cs
…on https://github.com/aloneguid/parquet-dotnet/issues/329
=> Added deserialization by rowGroupIndex

.github/workflows/full.yml, docs/README.md, src/Parquet.Test/Types/EndToEndTypeTest.cs, src/Parquet/Extensions/UntypedArrayExtensions.cs, src/Parquet/Extensions/UntypedArrayExtensions.tt, src/Parquet/Parquet.csproj
=> support for serialisation of nullable guids

src/Parquet/Extensions/UntypedArrayExtensions.cs, src/Parquet/Extensions/UntypedArrayExtensions.tt
=> Support of DateOnly type in UntypedArrayExtensions

src/Parquet.Test/Serialisation/ParquetSerializerTest.cs, src/Parquet/ParquetOptions.cs, src/Parquet/ParquetRowGroupReader.cs, src/Parquet/Serialization/ParquetSerializer.cs
=> Add SkipDeserializingMissingColumns option to allow handling missing fields in files gracefully

docs/release-history.md, src/Parquet.Test/Encodings/DeltaBinaryPackedEncodingTest.cs, src/Parquet.Test/Encodings/RleEncoderTest.cs, src/Parquet.Test/Extensions/EncodingExtensionsTest.cs, src/Parquet/Encodings/DeltaBinaryPackedEncoder.Variations.cs, src/Parquet/Encodings/DeltaBinaryPackedEncoder.Variations.tt, src/Parquet/Encodings/DeltaBinaryPackedEncoder.cs, src/Parquet/Encodings/RleBitpackedHybridEncoder.cs, src/Parquet/Extensions/EncodingExtensions.cs, src/Parquet/Extensions/OtherExtensions.cs, src/Parquet/Extensions/SpanExtensions.cs, src/Parquet/Extensions/StreamExtensions.cs, src/Parquet/File/DataColumnReader.cs, src/Parquet/File/DataColumnWriter.cs, src/Parquet/File/ThriftFooter.cs, src/Parquet/Parquet.csproj, src/Parquet/Schema/DataField.cs
The main work is done by @ee-naveen in #382. This PR is mostly a copy with some cleanups.
=> Delta binary packed encoding support on write

src/Parquet.Test/Encodings/DeltaBinaryPackedEncodingTest.cs, src/Parquet/Encodings/DeltaBinaryPackedEncoder.Variations.cs, src/Parquet/Encodings/DeltaBinaryPackedEncoder.Variations.tt
[DELTA_BINARY_PACKED Decoding]: Adding first value to destination array before reading the block
#389
=> [DELTA_BINARY_PACKED Decoding]: Adding first value to destination array before reading the block

src/Parquet.Test/Serialisation/ParquetSerializerTest.cs, src/Parquet.Test/Serialisation/SchemaReflectorTest.cs, src/Parquet/Serialization/TypeExtensions.cs
Specify ClrPropName when making StructField and ListField
#410
=> Support custom property names on struct and list fields

docs/README.md
Please add my PowerShell module to your Used by section
=> Add to Used by

src/Parquet/Serialization/ParquetSerializer.cs
fixes #411 
This just adds some basic locking around the static caches.
=> adds basic locking around static caches of stripers and assemblers

src/NetBox.cs, src/Parquet.Test/Serialisation/SchemaReflectorTest.cs, src/Parquet.Test/TestBase.cs, src/Parquet.Test/Types/EndToEndTypeTest.cs, src/Parquet/Encodings/ParquetPlainEncoder.cs, src/Parquet/Encodings/SchemaEncoder.cs, src/Parquet/Extensions/OtherExtensions.cs, src/Parquet/Schema/DateTimeFormat.cs, src/Parquet/Serialization/Attributes/ParquetTimestampAttribute.cs, src/Parquet/Serialization/TypeExtensions.cs, wrs/topics/serialisation.md
=> Support for writing DateTime with microsecond precision

docs/README.md
Hi,
We are relying on parquet-dotnet to load large amounts of data into data warehouses, such as Azure Synapse, Fabric Lakehouse, Fabric DataWarehouse, and Snowflake.
It's been rock-solid and very performant, super-happy with it.
=> Link to Omni Loader in Used by section

src/Parquet.Test/DataAnalysis/DataFrameReaderTest.cs, src/Parquet/Data/Analysis/DataFrameMapper.cs, src/Parquet/Data/Analysis/DataFrameMapper.tt
=> fix DataFrame loading doesn't support int16/uint16 types

docs/README.md
Added "Contoso Data Generator V2" into "Used by" section in readme.md
=> readme.md : Contoso Data Generator V2 link

src/Parquet.Test/Serialisation/ParquetSerializerTest.cs, src/Parquet/Serialization/ParquetSerializer.cs
Added untyped async enumable deserialization so that we do not have to load the whole data into memory.
=> Added untyped async enumable deserialization

wrs/topics/serialisation.md
This fixes a Typo in the Docs in serialisation.md
=> Fix Typo in serialisation.md

docs/README.md
=> Update README.md - remove duplicated nuget badge
